"""add document counter table

Revision ID: 09fa80289b41
Revises: fa603e4a8750
Create Date: 2026-03-29 12:16:33.081244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09fa80289b41'
down_revision: Union[str, None] = 'fa603e4a8750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_counter',
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('total_doc_created', sa.Integer(), nullable=False),
    sa.Column('total_doc_verified', sa.Integer(), nullable=False),
    sa.Column('total_doc_transferred', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('document_type')
    )
    op.drop_column('files', 'verification_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('verification_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('document_counter')
    # ### end Alembic commands ###
