"""Initial schema with all tables

Revision ID: 2ccc538c528b
Revises: 
Create Date: 2026-03-09 10:14:32.500874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ccc538c528b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('admin_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('admin_role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_admin_email', 'admin_users', ['email'], unique=False)
    op.create_index('idx_admin_role', 'admin_users', ['admin_role'], unique=False)
    op.create_table('permissions',
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('can_invite_users', sa.Boolean(), nullable=False),
    sa.Column('can_remove_users', sa.Boolean(), nullable=False),
    sa.Column('can_change_user_roles', sa.Boolean(), nullable=False),
    sa.Column('can_update_company_info', sa.Boolean(), nullable=False),
    sa.Column('can_change_plan', sa.Boolean(), nullable=False),
    sa.Column('can_update_payment', sa.Boolean(), nullable=False),
    sa.Column('can_delete_company', sa.Boolean(), nullable=False),
    sa.Column('can_view_billing', sa.Boolean(), nullable=False),
    sa.Column('can_create_shipments', sa.Boolean(), nullable=False),
    sa.Column('can_issue_documents', sa.Boolean(), nullable=False),
    sa.Column('can_delete_documents', sa.Boolean(), nullable=False),
    sa.Column('can_verify_documents', sa.Boolean(), nullable=False),
    sa.Column('can_view_analytics', sa.Boolean(), nullable=False),
    sa.Column('can_export_data', sa.Boolean(), nullable=False),
    sa.Column('can_view_audit_logs', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('plan_category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('plan',
    sa.Column('plan_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('plan_slug', sa.String(length=100), nullable=False),
    sa.Column('tier_level', sa.Integer(), nullable=False),
    sa.Column('base_price_aud', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_contract_pricing', sa.Boolean(), nullable=False),
    sa.Column('included_users', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('additional_user_price_aud', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('included_shipments', sa.Integer(), nullable=True),
    sa.Column('included_verifications', sa.Integer(), nullable=True),
    sa.Column('included_evidence_bundles', sa.Integer(), nullable=True),
    sa.Column('overage_price_per_shipment_aud', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('overage_price_per_verification_aud', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('has_hard_cap', sa.Boolean(), nullable=False),
    sa.Column('has_api_access', sa.Boolean(), nullable=False),
    sa.Column('has_bulk_verification', sa.Boolean(), nullable=False),
    sa.Column('has_branded_portal', sa.Boolean(), nullable=False),
    sa.Column('has_audit_logs', sa.Boolean(), nullable=False),
    sa.Column('has_priority_support', sa.Boolean(), nullable=False),
    sa.Column('has_sla', sa.Boolean(), nullable=False),
    sa.Column('has_multi_party_transfer', sa.Boolean(), nullable=False),
    sa.Column('has_advanced_controls', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['plan_category.category_id'], ),
    sa.PrimaryKeyConstraint('plan_id'),
    sa.UniqueConstraint('plan_slug')
    )
    op.create_index('idx_plan_category', 'plan', ['category_id'], unique=False)
    op.create_index('idx_plan_slug', 'plan', ['plan_slug'], unique=False)
    op.create_table('company',
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_type', sa.String(length=50), nullable=False),
    sa.Column('abn', sa.String(length=20), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('is_custom_contract', sa.Boolean(), nullable=False),
    sa.Column('custom_monthly_price_aud', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custom_annual_price_aud', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custom_setup_fee_aud', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custom_shipments_limit', sa.Integer(), nullable=True),
    sa.Column('custom_verifications_limit', sa.Integer(), nullable=True),
    sa.Column('custom_users_limit', sa.Integer(), nullable=True),
    sa.Column('custom_storage_gb', sa.Integer(), nullable=True),
    sa.Column('contract_start_date', sa.Date(), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('contract_renewal_type', sa.String(length=20), nullable=True),
    sa.Column('contract_document_url', sa.String(length=500), nullable=True),
    sa.Column('signed_by', sa.String(length=255), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('sla_uptime_guarantee', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sla_support_response_hours', sa.Integer(), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=False),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('subscription_started', sa.DateTime(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.plan_id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index('idx_company_plan', 'company', ['plan_id'], unique=False)
    op.create_index('idx_company_status', 'company', ['subscription_status'], unique=False)
    op.create_index('idx_company_type', 'company', ['company_type'], unique=False)
    op.create_table('company_usage',
    sa.Column('usage_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('billing_period_start', sa.Date(), nullable=False),
    sa.Column('billing_period_end', sa.Date(), nullable=False),
    sa.Column('shipments_created', sa.Integer(), nullable=False),
    sa.Column('documents_created', sa.Integer(), nullable=False),
    sa.Column('verifications_performed', sa.Integer(), nullable=False),
    sa.Column('evidence_bundles_created', sa.Integer(), nullable=False),
    sa.Column('storage_used_gb', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active_user_count', sa.Integer(), nullable=False),
    sa.Column('peak_user_count', sa.Integer(), nullable=False),
    sa.Column('shipment_overage', sa.Integer(), nullable=False),
    sa.Column('verification_overage', sa.Integer(), nullable=False),
    sa.Column('user_overage', sa.Integer(), nullable=False),
    sa.Column('overage_charges_aud', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('additional_charges_aud', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_charges_aud', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('invoice_id', sa.String(length=100), nullable=True),
    sa.Column('invoice_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_index('idx_usage_company', 'company_usage', ['company_id', 'billing_period_end'], unique=False)
    op.create_index('idx_usage_period', 'company_usage', ['billing_period_start', 'billing_period_end'], unique=False)
    op.create_table('contract_negotiations',
    sa.Column('negotiation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('requested_shipments', sa.Integer(), nullable=True),
    sa.Column('requested_verifications', sa.Integer(), nullable=True),
    sa.Column('requested_users', sa.Integer(), nullable=False),
    sa.Column('requested_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('proposed_monthly_price_aud', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('proposed_annual_price_aud', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('proposed_setup_fee_aud', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sales_rep_id', sa.String(length=100), nullable=False),
    sa.Column('customer_contact_email', sa.String(length=255), nullable=False),
    sa.Column('customer_contact_name', sa.String(length=255), nullable=False),
    sa.Column('proposal_document_url', sa.String(length=500), nullable=True),
    sa.Column('quote_valid_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('negotiation_id')
    )
    op.create_index('idx_negotiation_company', 'contract_negotiations', ['company_id'], unique=False)
    op.create_index('idx_negotiation_status', 'contract_negotiations', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('wallet_address', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('invited_by', sa.String(length=100), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('invitation_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role'], ['permissions.role'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_user_company', 'users', ['company_id'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_table('address_book',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('contact_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_index('idx_address_company', 'address_book', ['company_id'], unique=False)
    op.create_index('idx_address_type', 'address_book', ['contact_type'], unique=False)
    op.create_table('folder',
    sa.Column('folder_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_folder_id', sa.Integer(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['folder.folder_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('folder_id')
    )
    op.create_index('idx_folder_company', 'folder', ['company_id'], unique=False)
    op.create_index('idx_folder_user', 'folder', ['user_id'], unique=False)
    op.create_table('logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_category', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_log_action', 'logs', ['action_type', 'created_at'], unique=False)
    op.create_index('idx_log_company', 'logs', ['company_id', 'created_at'], unique=False)
    op.create_index('idx_log_resource', 'logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_log_user', 'logs', ['user_id', 'created_at'], unique=False)
    op.create_table('shipment',
    sa.Column('shipment_id', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=100), nullable=False),
    sa.Column('shipment_name', sa.String(length=255), nullable=False),
    sa.Column('shipment_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_index('idx_shipment_company', 'shipment', ['company_id'], unique=False)
    op.create_index('idx_shipment_created', 'shipment', ['created_at'], unique=False)
    op.create_index('idx_shipment_status', 'shipment', ['status'], unique=False)
    op.create_table('signature_library',
    sa.Column('signature_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('signature_name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('signature_id')
    )
    op.create_index('idx_signature_company', 'signature_library', ['company_id'], unique=False)
    op.create_index('idx_signature_default', 'signature_library', ['user_id', 'is_default'], unique=False)
    op.create_index('idx_signature_user', 'signature_library', ['user_id'], unique=False)
    op.create_table('files',
    sa.Column('file_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credential_id', sa.String(length=255), nullable=True),
    sa.Column('token_id', sa.String(length=255), nullable=True),
    sa.Column('token_registry', sa.String(length=255), nullable=True),
    sa.Column('blockchain_network', sa.String(length=50), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_error_code', sa.String(length=100), nullable=True),
    sa.Column('verification_error_message', sa.Text(), nullable=True),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('verification_link', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('verification_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.folder_id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.shipment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index('idx_file_company', 'files', ['company_id', 'created_at'], unique=False)
    op.create_index('idx_file_credential', 'files', ['credential_id'], unique=False)
    op.create_index('idx_file_shipment', 'files', ['shipment_id'], unique=False)
    op.create_index('idx_file_token', 'files', ['token_id'], unique=False)
    op.create_index('idx_file_verified', 'files', ['is_verified'], unique=False)
    op.create_table('document_verification',
    sa.Column('verification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('verified_by_company_id', sa.String(length=100), nullable=True),
    sa.Column('verified_by_user_id', sa.String(length=100), nullable=True),
    sa.Column('verifier_wallet_address', sa.String(length=255), nullable=True),
    sa.Column('verification_type', sa.String(length=50), nullable=False),
    sa.Column('verification_channel', sa.String(length=50), nullable=False),
    sa.Column('verification_result', sa.String(length=50), nullable=False),
    sa.Column('verification_error_code', sa.String(length=100), nullable=True),
    sa.Column('verification_error_message', sa.Text(), nullable=True),
    sa.Column('tradetrust_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ),
    sa.ForeignKeyConstraint(['verified_by_company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('verification_id')
    )
    op.create_index('idx_verification_company', 'document_verification', ['verified_by_company_id', 'verified_at'], unique=False)
    op.create_index('idx_verification_file', 'document_verification', ['file_id', 'verified_at'], unique=False)
    op.create_index('idx_verification_type', 'document_verification', ['verification_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_verification_type', table_name='document_verification')
    op.drop_index('idx_verification_file', table_name='document_verification')
    op.drop_index('idx_verification_company', table_name='document_verification')
    op.drop_table('document_verification')
    op.drop_index('idx_file_verified', table_name='files')
    op.drop_index('idx_file_token', table_name='files')
    op.drop_index('idx_file_shipment', table_name='files')
    op.drop_index('idx_file_credential', table_name='files')
    op.drop_index('idx_file_company', table_name='files')
    op.drop_table('files')
    op.drop_index('idx_signature_user', table_name='signature_library')
    op.drop_index('idx_signature_default', table_name='signature_library')
    op.drop_index('idx_signature_company', table_name='signature_library')
    op.drop_table('signature_library')
    op.drop_index('idx_shipment_status', table_name='shipment')
    op.drop_index('idx_shipment_created', table_name='shipment')
    op.drop_index('idx_shipment_company', table_name='shipment')
    op.drop_table('shipment')
    op.drop_index('idx_log_user', table_name='logs')
    op.drop_index('idx_log_resource', table_name='logs')
    op.drop_index('idx_log_company', table_name='logs')
    op.drop_index('idx_log_action', table_name='logs')
    op.drop_table('logs')
    op.drop_index('idx_folder_user', table_name='folder')
    op.drop_index('idx_folder_company', table_name='folder')
    op.drop_table('folder')
    op.drop_index('idx_address_type', table_name='address_book')
    op.drop_index('idx_address_company', table_name='address_book')
    op.drop_table('address_book')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_company', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_negotiation_status', table_name='contract_negotiations')
    op.drop_index('idx_negotiation_company', table_name='contract_negotiations')
    op.drop_table('contract_negotiations')
    op.drop_index('idx_usage_period', table_name='company_usage')
    op.drop_index('idx_usage_company', table_name='company_usage')
    op.drop_table('company_usage')
    op.drop_index('idx_company_type', table_name='company')
    op.drop_index('idx_company_status', table_name='company')
    op.drop_index('idx_company_plan', table_name='company')
    op.drop_table('company')
    op.drop_index('idx_plan_slug', table_name='plan')
    op.drop_index('idx_plan_category', table_name='plan')
    op.drop_table('plan')
    op.drop_table('plan_category')
    op.drop_table('permissions')
    op.drop_index('idx_admin_role', table_name='admin_users')
    op.drop_index('idx_admin_email', table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
