"""add credits and plan limits

Revision ID: 38d5b7d46adf
Revises: 2cdee4a58e6c
Create Date: 2026-03-17 15:32:32.639695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d5b7d46adf'
down_revision: Union[str, None] = '2cdee4a58e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_credits',
    sa.Column('credit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('billing_period_start', sa.Date(), nullable=False),
    sa.Column('billing_period_end', sa.Date(), nullable=False),
    sa.Column('package_credits_remaining', sa.Integer(), nullable=False),
    sa.Column('package_credits_purchased', sa.Integer(), nullable=False),
    sa.Column('total_credit_spend_aud', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('credit_id')
    )
    op.create_index('idx_credits_company', 'company_credits', ['company_id', 'billing_period_end'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('credit_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_credit_aud', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price_aud', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('idx_credit_tx_company', 'credit_transactions', ['company_id', 'created_at'], unique=False)
    op.create_index('idx_credit_tx_payment', 'credit_transactions', ['stripe_payment_intent_id'], unique=False)
    op.add_column('company_usage', sa.Column('transfers_performed', sa.Integer(), nullable=False))
    op.add_column('company_usage', sa.Column('transfer_overage', sa.Integer(), nullable=False))
    op.add_column('plan', sa.Column('included_transfers', sa.Integer(), nullable=True))
    op.add_column('plan', sa.Column('max_overage_packages', sa.Integer(), nullable=True))
    op.add_column('plan', sa.Column('issuance_price_aud', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('plan', sa.Column('value_cap_aud', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'value_cap_aud')
    op.drop_column('plan', 'issuance_price_aud')
    op.drop_column('plan', 'max_overage_packages')
    op.drop_column('plan', 'included_transfers')
    op.drop_column('company_usage', 'transfer_overage')
    op.drop_column('company_usage', 'transfers_performed')
    op.drop_index('idx_credit_tx_payment', table_name='credit_transactions')
    op.drop_index('idx_credit_tx_company', table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index('idx_credits_company', table_name='company_credits')
    op.drop_table('company_credits')
    # ### end Alembic commands ###
