"""add wallet_address to address_book and make contact_type nullable

Revision ID: 5231e72a7034
Revises: 3344b6689f2d
Create Date: 2026-04-08 10:57:34.232857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5231e72a7034'
down_revision: Union[str, None] = '3344b6689f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_book', sa.Column('wallet_address', sa.String(length=255), nullable=False))
    op.alter_column('address_book', 'contact_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address_book', 'contact_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('address_book', 'wallet_address')
    # ### end Alembic commands ###
