"""add types column to files

Revision ID: 76e8f98dc818
Revises: 5231e72a7034
Create Date: 2026-04-27 01:22:53.317690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e8f98dc818'
down_revision: Union[str, None] = '5231e72a7034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('types', sa.String(length=50), nullable=False, server_default='verifiable'))
    op.alter_column('files', 'types', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'types')
    # ### end Alembic commands ###
