"""add surrender_price_aud to plan table

Revision ID: bdad19818163
Revises: 09fa80289b41
Create Date: 2026-03-31 14:53:52.210630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdad19818163'
down_revision: Union[str, None] = '09fa80289b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('surrender_price_aud', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'surrender_price_aud')
    # ### end Alembic commands ###
