"""add stripe columns

Revision ID: fa603e4a8750
Revises: 38d5b7d46adf
Create Date: 2026-03-25 14:43:40.950825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa603e4a8750'
down_revision: Union[str, None] = '38d5b7d46adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True))
    op.add_column('plan', sa.Column('stripe_price_id_monthly', sa.String(length=100), nullable=True))
    op.add_column('plan', sa.Column('stripe_price_id_anually', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'stripe_price_id_anually')
    op.drop_column('plan', 'stripe_price_id_monthly')
    op.drop_column('company', 'stripe_subscription_id')
    # ### end Alembic commands ###
